set tabstop=4 softtabstop=4 shiftwidth=4 expandtab
set smartindent
set ruler
set relativenumber
set nu
set hidden
set nowrap
set noswapfile
set nobackup
set incsearch
set scrolloff=16
set signcolumn=yes
set colorcolumn=120
set cmdheight=2
set updatetime=50
